# Generated by Django 3.1.7 on 2021-03-11 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_checker', '0002_auto_20210311_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.CreateModel(
            name='CSVFileResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('write_date', models.DateTimeField(auto_now=True, null=True)),
                ('csv_file_result', models.TextField(max_length=128)),
                ('csv_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='CSVFileResults', to='email_checker.csvfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
