# Generated by Django 3.1.7 on 2021-03-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_checker', '0003_auto_20210311_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='available',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(upload_to=''),
        ),
    ]
