# Generated by Django 3.1.7 on 2021-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_checker', '0004_auto_20210312_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='accessible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='available',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='catchall',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='valid',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
