# Generated by Django 3.1.7 on 2021-03-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_checker', '0005_auto_20210312_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='available',
        ),
    ]
